# Generated by Django 4.1.7 on 2023-07-26 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('fixed_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('min_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('max_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('date_ads_posted', models.DateTimeField(auto_now_add=True)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('clicks_timestamp', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_favorites', models.BooleanField(default=False)),
                ('is_vip', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonce', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
