# Generated by Django 4.1.7 on 2023-07-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Annonce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='lattitude',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='annonce',
            name='longitude',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='fixed_price',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='max_price',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True),
        ),
    ]
