# Generated by Django 4.1.7 on 2023-07-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Annonce', '0002_annonce_lattitude_annonce_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annonce',
            name='lattitude',
        ),
        migrations.AddField(
            model_name='annonce',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
