# Generated by Django 4.1.7 on 2023-08-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Annonce', '0003_remove_annonce_lattitude_annonce_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='slug',
            field=models.SlugField(default='', max_length=200, unique=True),
        ),
    ]
