# Generated by Django 4.1.7 on 2023-08-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Annonce', '0004_annonce_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
